import {
  type RecipeTemplate,
  type TemplateId,
} from "./types";

export const recipeTemplates: Record<TemplateId, RecipeTemplate> = {
  kartoffelgratin: {
    id: "kartoffelgratin",
    name: "Kartoffelgratin",
    basePortions: 10,
    targetPortions: 80,
    ingredients: [
      {
        name: "Kartoffeln, mehligkochend",
        base: 2.5,
        unit: "kg",
        loss: 15,
        demandUnit: "kg",
        purchase: { orderUnit: "Sack/Säcke", packageSize: 25, packageSizeUnit: "kg", rounding: "whole" },
      },
      {
        name: "Sahne",
        base: 1.2,
        unit: "l",
        loss: 0,
        demandUnit: "l",
        purchase: { orderUnit: "Flasche(n)", packageSize: 1, packageSizeUnit: "l", rounding: "whole" },
      },
      {
        name: "Milch",
        base: 0.6,
        unit: "l",
        loss: 0,
        demandUnit: "l",
        purchase: { orderUnit: "Karton(s)", packageSize: 12, packageSizeUnit: "l", rounding: "whole" },
      },
      {
        name: "Reibekäse",
        base: 0.65,
        unit: "kg",
        loss: 3,
        demandUnit: "kg",
        purchase: { orderUnit: "Packung(en)", packageSize: 1, packageSizeUnit: "kg", rounding: "whole" },
      },
      {
        name: "Butter",
        base: 0.12,
        unit: "kg",
        loss: 0,
        demandUnit: "kg",
        purchase: { orderUnit: "Packung(en)", packageSize: 0.25, packageSizeUnit: "kg", rounding: "whole" },
      },
      {
        name: "Knoblauch",
        base: 12,
        unit: "Zehen",
        loss: 10,
        demandUnit: "Zehen",
        purchase: {
          orderUnit: "kg",
          packageSize: 1,
          packageSizeUnit: "kg",
          rounding: "none",
          approximate: true,
          conversion: { fromUnit: "Zehen", toUnit: "kg", fromPerTo: 200 },
        },
      },
      {
        name: "Salz",
        base: 3,
        unit: "EL",
        loss: 0,
        demandUnit: "EL",
        purchase: { orderUnit: "Packung(en)", packageSize: 55, packageSizeUnit: "EL", rounding: "whole", approximate: true },
      },
      {
        name: "Muskat",
        base: 2,
        unit: "TL",
        loss: 0,
        demandUnit: "TL",
        purchase: { orderUnit: "Dose(n)", packageSize: 25, packageSizeUnit: "TL", rounding: "whole", approximate: true },
      },
    ],
  },
  bolognese: {
    id: "bolognese",
    name: "Bolognese-Sauce",
    basePortions: 20,
    targetPortions: 100,
    ingredients: [
      {
        name: "Rinderhackfleisch",
        base: 4.5,
        unit: "kg",
        loss: 2,
        demandUnit: "kg",
        purchase: { orderUnit: "Packung(en)", packageSize: 1, packageSizeUnit: "kg", rounding: "whole" },
      },
      {
        name: "Zwiebeln",
        base: 1.2,
        unit: "kg",
        loss: 12,
        demandUnit: "kg",
        purchase: { orderUnit: "Sack/Säcke", packageSize: 10, packageSizeUnit: "kg", rounding: "whole" },
      },
      {
        name: "Karotten",
        base: 1.1,
        unit: "kg",
        loss: 15,
        demandUnit: "kg",
        purchase: { orderUnit: "Sack/Säcke", packageSize: 10, packageSizeUnit: "kg", rounding: "whole" },
      },
      {
        name: "Staudensellerie",
        base: 0.8,
        unit: "kg",
        loss: 18,
        demandUnit: "kg",
        purchase: { orderUnit: "Bund", packageSize: 0.5, packageSizeUnit: "kg", rounding: "whole", approximate: true },
      },
      {
        name: "Tomatenpassata",
        base: 6,
        unit: "l",
        loss: 0,
        demandUnit: "l",
        purchase: { orderUnit: "Karton(s)", packageSize: 12, packageSizeUnit: "l", rounding: "whole" },
      },
      {
        name: "Tomatenmark",
        base: 0.45,
        unit: "kg",
        loss: 0,
        demandUnit: "kg",
        purchase: { orderUnit: "Dose(n)", packageSize: 0.8, packageSizeUnit: "kg", rounding: "whole" },
      },
      {
        name: "Rotwein",
        base: 1.2,
        unit: "l",
        loss: 0,
        demandUnit: "l",
        purchase: { orderUnit: "Flasche(n)", packageSize: 0.75, packageSizeUnit: "l", rounding: "whole" },
      },
      {
        name: "Olivenöl",
        base: 0.25,
        unit: "l",
        loss: 0,
        demandUnit: "l",
        purchase: { orderUnit: "Flasche(n)", packageSize: 1, packageSizeUnit: "l", rounding: "whole" },
      },
      {
        name: "Knoblauch",
        base: 16,
        unit: "Zehen",
        loss: 10,
        demandUnit: "Zehen",
        purchase: {
          orderUnit: "kg",
          packageSize: 1,
          packageSizeUnit: "kg",
          rounding: "none",
          approximate: true,
          conversion: { fromUnit: "Zehen", toUnit: "kg", fromPerTo: 200 },
        },
      },
      {
        name: "Oregano, getrocknet",
        base: 25,
        unit: "g",
        loss: 0,
        demandUnit: "g",
        purchase: { orderUnit: "Dose(n)", packageSize: 100, packageSizeUnit: "g", rounding: "whole" },
      },
    ],
  },
};
